-- ==========================================
-- NOX NETWORK v2.5 - Full Database Schema
-- Run this in Supabase SQL Editor
-- ==========================================

-- ==========================================
-- 1. TABLES
-- ==========================================

-- Users table
CREATE TABLE IF NOT EXISTS users (
  tg_id BIGINT PRIMARY KEY,
  role VARCHAR(20) DEFAULT 'user',
  balance_days INT DEFAULT 0,
  nxc_balance INT DEFAULT 0,
  auto_refill BOOLEAN DEFAULT FALSE,
  referred_by BIGINT,
  referral_count INT DEFAULT 0,
  ambassador_points INT DEFAULT 0,
  vless_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- AI History table (with request_id for webhook matching)
CREATE TABLE IF NOT EXISTS ai_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_id BIGINT REFERENCES users(tg_id),
  type VARCHAR(20) NOT NULL,
  prompt TEXT NOT NULL,
  result TEXT,
  model VARCHAR(100),
  request_id VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Transactions table
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_id BIGINT REFERENCES users(tg_id),
  amount INT NOT NULL,
  type VARCHAR(50) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Giveaway entries table
CREATE TABLE IF NOT EXISTS giveaway_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_id BIGINT REFERENCES users(tg_id),
  giveaway_id VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(tg_id, giveaway_id)
);

-- Payments table
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tg_id BIGINT REFERENCES users(tg_id),
  amount INT NOT NULL,
  plan VARCHAR(50) NOT NULL,
  method VARCHAR(20) NOT NULL, -- yookassa/stars/ton
  status VARCHAR(20) DEFAULT 'pending',
  external_id VARCHAR(100),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 2. ROW LEVEL SECURITY (RLS)
-- ==========================================

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE giveaway_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Users policies
DROP POLICY IF EXISTS "Users can view own profile" ON users;
CREATE POLICY "Users can view own profile" ON users FOR SELECT USING (auth.uid()::text = tg_id::text);

-- AI History policies
DROP POLICY IF EXISTS "Users can view own AI history" ON ai_history;
CREATE POLICY "Users can view own AI history" ON ai_history FOR SELECT USING (auth.uid()::text = tg_id::text);

-- Transactions policies
DROP POLICY IF EXISTS "Users can view own transactions" ON transactions;
CREATE POLICY "Users can view own transactions" ON transactions FOR SELECT USING (auth.uid()::text = tg_id::text);

-- Giveaway entries policies
CREATE POLICY "Users can view own giveaway entries" ON giveaway_entries FOR SELECT USING (auth.uid()::text = tg_id::text);
CREATE POLICY "Users can insert own giveaway entries" ON giveaway_entries FOR INSERT WITH CHECK (auth.uid()::text = tg_id::text);

-- ==========================================
-- 3. FUNCTIONS
-- ==========================================

-- Atomic NXC Deduction Function
CREATE OR REPLACE FUNCTION deduct_nxc(target_tg_id BIGINT, amount INT)
RETURNS JSON AS $$
DECLARE
  current_balance INT;
BEGIN
  SELECT nxc_balance INTO current_balance FROM users WHERE tg_id = target_tg_id FOR UPDATE;
  
  IF current_balance IS NULL THEN
    RETURN json_build_object('success', false, 'error', 'User not found');
  END IF;
  
  IF current_balance < amount THEN
    RETURN json_build_object('success', false, 'error', 'Insufficient balance');
  END IF;
  
  UPDATE users SET nxc_balance = nxc_balance - amount WHERE tg_id = target_tg_id;
  
  RETURN json_build_object('success', true, 'new_balance', current_balance - amount);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Atomic Balance Increment (for payments/admins)
CREATE OR REPLACE FUNCTION add_nxc_and_days(target_tg_id BIGINT, days_to_add INT, nxc_to_add INT)
RETURNS JSON AS $$
BEGIN
  INSERT INTO users (tg_id, balance_days, nxc_balance)
  VALUES (target_tg_id, days_to_add, nxc_to_add)
  ON CONFLICT (tg_id) 
  DO UPDATE SET 
    balance_days = users.balance_days + EXCLUDED.balance_days,
    nxc_balance = users.nxc_balance + EXCLUDED.nxc_balance;
    
  RETURN json_build_object('success', true);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get User Rank based on ambassador points
CREATE OR REPLACE FUNCTION get_user_rank(user_tg_id BIGINT)
RETURNS JSON AS $$
DECLARE
  u_points INT;
  u_rank INT;
  t_users INT;
BEGIN
  SELECT COALESCE(ambassador_points, 0) INTO u_points 
  FROM users 
  WHERE tg_id = user_tg_id;
  
  IF u_points IS NULL THEN
    u_points := 0;
  END IF;

  SELECT count(*) + 1 INTO u_rank 
  FROM users 
  WHERE ambassador_points > u_points;
  
  SELECT count(*) INTO t_users FROM users;
  
  IF t_users = 0 THEN 
    t_users := 1;
    u_rank := 1;
  END IF;

  RETURN json_build_object('rank', u_rank, 'total', t_users);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Update referral_count automatically on insert
CREATE OR REPLACE FUNCTION increment_referral_count()
RETURNS trigger AS $$
BEGIN
  IF NEW.referred_by IS NOT NULL THEN
    -- Referrer reward
    UPDATE users SET 
      referral_count = referral_count + 1,
      ambassador_points = ambassador_points + 100,
      balance_days = balance_days + 10
    WHERE tg_id = NEW.referred_by;
    
    -- Referred user reward
    UPDATE users SET 
      balance_days = balance_days + 7,
      nxc_balance = nxc_balance + 150
    WHERE tg_id = NEW.tg_id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Cleanup old AI history (7 days TTL)
CREATE OR REPLACE FUNCTION delete_old_history()
RETURNS trigger AS $$
BEGIN
  DELETE FROM ai_history WHERE created_at < NOW() - INTERVAL '7 days';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Smart Auto-Refill (cron job)
CREATE OR REPLACE FUNCTION process_auto_refills()
RETURNS void AS $$
BEGIN
  UPDATE users 
  SET 
    nxc_balance = nxc_balance - 399,
    balance_days = 30
  WHERE 
    auto_refill = TRUE 
    AND balance_days <= 0 
    AND nxc_balance >= 399;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 4. TRIGGERS
-- ==========================================

DROP TRIGGER IF EXISTS tr_after_user_insert ON users;
CREATE TRIGGER tr_after_user_insert
  AFTER INSERT ON users
  FOR EACH ROW
  EXECUTE FUNCTION increment_referral_count();

DROP TRIGGER IF EXISTS trigger_delete_old_history ON ai_history;
CREATE TRIGGER trigger_delete_old_history
  AFTER INSERT ON ai_history
  EXECUTE FUNCTION delete_old_history();

-- Stats function for admin bot
CREATE OR REPLACE FUNCTION get_detailed_stats()
RETURNS TABLE (
  total_users BIGINT,
  active_users BIGINT,
  total_nxc BIGINT,
  new_users_24h BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    (SELECT COUNT(*) FROM users)::BIGINT as total_users,
    (SELECT COUNT(*) FROM users WHERE balance_days > 0)::BIGINT as active_users,
    (SELECT COALESCE(SUM(nxc_balance), 0) FROM users)::BIGINT as total_nxc,
    (SELECT COUNT(*) FROM users WHERE created_at > NOW() - INTERVAL '24 hours')::BIGINT as new_users_24h;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ==========================================
-- 5. INDICES
-- ==========================================

CREATE INDEX IF NOT EXISTS idx_users_ambassador_points ON users(ambassador_points DESC);
CREATE INDEX IF NOT EXISTS idx_users_referred_by ON users(referred_by);
CREATE INDEX IF NOT EXISTS idx_ai_history_tg_id ON ai_history(tg_id);
CREATE INDEX IF NOT EXISTS idx_transactions_tg_id ON transactions(tg_id);
CREATE INDEX IF NOT EXISTS idx_giveaway_entries_tg_id ON giveaway_entries(tg_id);
CREATE INDEX IF NOT EXISTS idx_payments_tg_id ON payments(tg_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);

-- ==========================================
-- 6. INITIAL ADMIN USER (опционально)
-- ==========================================

-- Раскомментируйте для создания администратора:
-- INSERT INTO users (tg_id, role, balance_days, nxc_balance) 
-- VALUES (7278863161, 'admin', 365, 10000)
-- ON CONFLICT (tg_id) DO UPDATE SET role = 'admin';
